apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-management.fullname" . }}-backend
  labels:
    app: {{ include "library-management.name" . }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8080
  selector:
    app: {{ include "library-management.name" . }}
    component: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-management.fullname" . }}-backend
  labels:
    app: {{ include "library-management.name" . }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "library-management.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "library-management.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "library-management.fullname" . }}-backend
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "library-management.fullname" . }}-postgres
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "library-management.fullname" . }}-postgres
                  key: password
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
