{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "library-management.fullname" . }}
  labels:
    app: {{ include "library-management.name" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "library-management.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "library-management.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
