apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-management.fullname" . }}-postgres
  labels:
    app: {{ include "library-management.name" . }}
type: Opaque
stringData:
  database: {{ .Values.postgresql.database | quote }}
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
